--- # roles/nginx_letsencrypt/tasks/main.yml

- name: ensure host volume directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nginx_webroot_volume_host_path }}"
    - "{{ nginx_confdir_volume_host_path }}"
    - "{{ letsencrypt_confdir_volume_host_path }}"
    - "{{ letsencrypt_statedir_volume_host_path }}"

- name: ensure webroot directories for each domain exist
  file:
    path: "{{ nginx_webroot_volume_host_path }}/{{ item }}"
    state: directory
  with_items: "{{ nginx_domains }}"

- name: copy static configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ nginx_confdir_volume_host_path }}/"
  with_items: "{{ ['config/'] | union(nginx_static_config | default([])) }}"

- name: copy static site files
  copy:
    src: "{{ item }}"
    dest: "{{ nginx_webroot_volume_host_path }}/"
  with_items: "{{ ['site/'] | union(nginx_static_site | default([])) }}"

- block:
  - name: stat ssl certificates
    stat:
      path: "{{ letsencrypt_confdir_volume_host_path }}/live/{{ item }}"
    register: ssl_stats
    with_items: "{{ nginx_domains }}"
  - set_fact:
      ssl_cert_exists: "{{ ssl_cert_exists | default({}) | combine({item.item: item.stat.exists}) }}"
    with_items: "{{ ssl_stats['results'] }}"
  - debug:
      msg: "ssl_cert_exists content: {{ ssl_cert_exists }}"
  - name: create configuration file for each domain
    template:
      src: "config/domain.conf.j2"
      dest: "{{ nginx_confdir_volume_host_path }}/{{ item }}.conf"
    with_items: "{{ nginx_domains }}"

- name: create initial index.html file for each domain
  template:
    src: "site/index.html.j2"
    dest: "{{ nginx_webroot_volume_host_path }}/{{ item }}/index.html"
  with_items: "{{ nginx_domains }}"
  when: not skip_intial_index_file

- name: create nginx container
  vars:
    container_name: "{{ nginx_container_name }}"
    container_state: running
    container_image: "{{ nginx_container_image }}"
    container_run_args: >-
      --rm
      --network "{{ podman_network_name }}"
      -v "{{ nginx_confdir_volume_host_path }}:/etc/nginx/conf.d:ro"
      -v "{{ nginx_webroot_volume_host_path }}:/usr/share/nginx/html"
      -v "{{ letsencrypt_confdir_volume_host_path }}:/etc/letsencrypt:ro"
      {% if nginx_http_ip is defined %}
      -p "{{ nginx_http_ip }}:{{ nginx_http_port }}:80"
      {% else %}
      -p "{{ nginx_http_port }}:80"
      {% endif %}
      {% if nginx_http_ip is defined %}
      -p "{{ nginx_https_ip }}:{{ nginx_https_port}}:443"
      {% else %}
      -p "{{ nginx_https_port}}:443"
      {% endif %}
    container_firewall_ports:
      - "{{ nginx_http_port }}/tcp"
      - "{{ nginx_https_port}}/tcp"
  include_role:
    name: podman_container_systemd

- name: wait for nginx to start
  wait_for: "port={{ nginx_http_port }} host={{ nginx_http_ip | default('localhost') }} delay=2 state=present timeout=60"
  when: container_state is not defined

- name: reload nginx config
  command: "podman exec {{ nginx_container_name }} nginx -s reload"
  when: container_state is not defined

- name: check whether letsencrypt account is already registered
  stat:
    path: "{{ letsencrypt_confdir_volume_host_path }}/accounts"
  register: letsencyrpt_accounts

- name: register letsencrypt account in certbot container
  vars:
    container_name: "{{ letsencrypt_container_name }}_register"
    container_state: running
    container_image: "{{ letsencrypt_container_image }}"
    container_run_args: >-
      --rm
      --network "{{ podman_network_name }}"
      -v "{{ letsencrypt_confdir_volume_host_path }}:/etc/letsencrypt"
      -v "{{ letsencrypt_statedir_volume_host_path }}:/var/lib/letsencrypt"
      -v "{{ nginx_webroot_volume_host_path }}:/usr/share/nginx/html"
    container_cmd_args: >-
      register
      -m "{{ letsencrypt_camail }}"
      --agree-tos
      --non-interactive
  include_role:
    name: podman_container_systemd
  when: not letsencyrpt_accounts.stat.exists and letsencrypt_domains is defined

- name: create or renew certificate using certbot container
  command:
    cmd: >-
      podman run
      --rm
      --network "{{ podman_network_name }}"
      -v "{{ letsencrypt_confdir_volume_host_path }}:/etc/letsencrypt"
      -v "{{ letsencrypt_statedir_volume_host_path }}:/var/lib/letsencrypt"
      -v "{{ nginx_webroot_volume_host_path }}:/usr/share/nginx/html"
      {{ letsencrypt_container_image }}
      certonly
      --webroot
      --webroot-path=/usr/share/nginx/html/{{ item }}
      -d "{{ item }}"
      -m "{{ letsencrypt_camail }}"
      --agree-tos
      --non-interactive
      --keep-until-expiring
  with_items: "{{ letsencrypt_domains | default([]) }}"
  when: container_state is not defined

- block:
  - name: stat ssl certificates (2nd round - post creation)
    stat:
      path: "{{ letsencrypt_confdir_volume_host_path }}/live/{{ item }}"
    register: ssl_stats
    with_items: "{{ nginx_domains }}"
  - set_fact:
      ssl_cert_exists: "{{ ssl_cert_exists | default({}) | combine({item.item: item.stat.exists}) }}"
    with_items: "{{ ssl_stats['results'] }}"
  - debug:
      msg: "ssl_cert_exists content: {{ ssl_cert_exists }}"
  - name: create configuration file for each domain (2nd round - post creation)
    template:
      src: "config/domain.conf.j2"
      dest: "{{ nginx_confdir_volume_host_path }}/{{ item }}.conf"
    with_items: "{{ nginx_domains }}"
  - name: reload nginx config
    command: "podman exec {{ nginx_container_name }} nginx -s reload"
    when: container_state is not defined
